version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=sqlite:///./iwc_sentiment.db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./logs:/app/logs
      - ./iwc_sentiment.db:/app/iwc_sentiment.db
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  celery:
    build: .
    command: celery -A app.main worker --loglevel=info
    environment:
      - DEBUG=true
      - DATABASE_URL=sqlite:///./iwc_sentiment.db
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./logs:/app/logs
      - ./iwc_sentiment.db:/app/iwc_sentiment.db
    depends_on:
      - redis
    restart: unless-stopped

  flower:
    build: .
    command: celery -A app.main flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: